### ISSUE TITLE
Add latest security patch for all supported versions

### ISSUE THREAD

**Issue by damien-biasotto** [bragento/magento-core#11]
There is a new security patch available for magento. Here is a gist with this patch for several magento versions from 1.4 to 1.9.

https://gist.github.com/4c123ecce0069918e006

**Comment by davidverholen** [comment]
Hi Damien,

first, thanks for that!

I'll merge them now, but I won't change the tags yet. The reason is, that composer won't trigger an update if I just change the reference of the Version tag. We have to think about if it's better, to add new versions for the patches or keep the original Magento versions.

If you don't want to wait, you can checkout the respective dev branch (e.g. 1.9.*@dev).

**Comment by Mohamed-GHARBI** [comment]
Hi Damien,

Thank you  for this work, 
but i can not find out  which patch i should apply and for which version .
for instance which one is to be applied on CE 1.7

**Comment by davidverholen** [comment]
the patche Versions are now released. Composer should now update to the patched Versions

**Comment by damien-biasotto** [comment]
Thanks a lot @davidverholen.

@Mohamed-GHARBI : You have to apply this one https://gist.github.com/damien-biasotto/4c123ecce0069918e006#file-supee-5345 for magento 1.7.x

**Comment by davidverholen** [comment]
ok, I just testet it. It won't take the patched Version, if you require 1.9.1.0, but if you require 1.9.1.* or 1.9.* for example
