### ISSUE TITLE
Missing LICENSE.html file when installing using browser

### ISSUE THREAD

**Issue by hostep** [bragento/magento-core#19]
Hi

This is the first time I use your project (or even Magento in combination with composer for that matter).
But upon trying to install Magento using a browser, I get this error:
```
There was a problem proceeding with Magento installation.

Please contact developers with error messages on this page.

Warning: file_get_contents(magento/LICENSE.html): failed to open stream: No such file or directory  in magento/app/code/core/Mage/Install/Block/Begin.php on line 68
```

You can most probably fix this by putting the LICENSE.html file in composer.json in the mapping.

**Comment by davidverholen** [comment]
hey, the reason for missing those files out was to have only the needed files in the magento root dir (the LICENSE.html seems to be needed in php strict mode apperently).

That was because people often forget to secure files like RELEASE_NOTES.txt.

Since the LICENSE.html does not contain any security related information, I think it should be O.K., to include it in the mapping

**Comment by hostep** [comment]
Yes I agree. To be sure, I just compared the LICENSE.html file between Magento 1.7.0.2 and 1.9.1.0 and they are 100% identical, so it shouldn't expose what version someone is using.

**Comment by davidverholen** [comment]
hey, I don't have much time currently, so I just added it to the 1.9 branch for now (since most new installs will be from that branch anyway) and made a new patch release

**Comment by hostep** [comment]
Cool, thanks!
